### ISSUE TITLE
Quick Start with vue is failing

### ISSUE THREAD

**Issue by tmamedbekov** [Sitecore/jss#360]
## Description
Quick Start with VUE is failing

## Expected behavior
I expect for it start locally without errors

## Steps To Reproduce
-npm install -g @sitecore-jss/sitecore-jss-cli
-jss create my-first-jss-app vue
-cd my-first-jss-app
-jss start
-error

## Possible Fix
Build is failing on the prettier
eslint-plugin-prettier

## Your Environment

* Sitecore Version: Disconnected Mode N/A
* JSS Version: Disconnected Mode N/A
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Mac OS Catalina
* Link to your project (if available): N/A

## Screenshots

![image](https://user-images.githubusercontent.com/21371923/79393261-9bfb7480-7f3a-11ea-99e3-89607ddd3f26.png)

**Comment by andrewcowley** [comment]
As a workaround removing `'@vue/prettier'` from .eslintrc.js bypasses this error.

**Comment by sc-illiakovalenko** [comment]
Fixed in #365

**Comment by shujaatxp** [comment]
This is a work around. Still -jss create my-first-jss-app vue , the module is still there or error is still persists. for every installation, i am facing the same.

**Comment by sc-illiakovalenko** [comment]
@shujaatxp I didn't release this fix, it's still in develop. I think you tested it with jss 13.0.5

**Comment by shujaatxp** [comment]
yes @sc-illiakovalenko : You were correct, i tested with 13.0.5. Thanks for the response.

**Comment by tmamedbekov** [comment]
We got a problem again

```
JSS Disconnected-mode Proxy is listening on port 3042. (PID: 5212)
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                                                                                          10:16:54 PM

 error  in ./src/main.js

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load plugin 'prettier' declared in '.eslintrc.js » @vue/eslint-config-prettier': Cannot find module 'eslint-plugin-prettier'
Require stack:
- /Users/sample-vue/__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.resolve (internal/modules/cjs/helpers.js:75:19)
    at Object.resolve (/Users/sample-vue/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadPlugin (/Users/sample-vue/node_modules/eslint/lib/cli-engine/config-array-factory.js:845:39)
    at /Users/sample-vue/node_modules/eslint/lib/cli-engine/config-array-factory.js:734:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/Users/sample-vue/node_modules/eslint/lib/cli-engine/config-array-factory.js:730:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/sample-vue/node_modules/eslint/lib/cli-engine/config-array-factory.js:554:32)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/sample-vue/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/sample-vue/node_modules/eslint/lib/cli-engine/config-array-factory.js:547:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/sample-vue/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/sample-vue/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)

 @ multi (webpack)-dev-server/client?http://192.168.1.27:3000/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
